import { categories as seedCategories, solutions as seedSolutions, slugify, CATEGORY_IDS } from '../../catalog-core/seed';
import { getSolutionCover } from '../../catalog-core/mappers';
import type { AdminCatalogRepository, AuthRepository, MediaRepository } from '../../catalog-core/repositories';
import type { AdminSolutionListItem, AdminSolutionQuery, CreateCategoryInput, CreateMediaUploadRequest, CreateSolutionInput, MediaUploadResultDto, OtpChallengeDto, PagedResult, ReorderCategoryItem, RequestOtpDto, UpdateCategoryInput, UpdateSolutionInput, VerifyOtpDto } from '../../catalog-core/contracts';
import type { AuthSession, ServiceCategory, Solution, SolutionMedia } from '../../catalog-core/models';

const SOLUTIONS = 'apx-admin-solutions'; const CATEGORIES = 'apx-admin-categories';
const read = <T>(key: string, seed: T): T => { try { const stored = localStorage.getItem(key); return stored ? JSON.parse(stored) as T : structuredClone(seed); } catch { return structuredClone(seed); } };
const save = <T>(key: string, value: T): T => { localStorage.setItem(key, JSON.stringify(value)); return structuredClone(value); };
const LEGACY_CATEGORY_IDS: Record<string, string> = { experiencias: CATEGORY_IDS.experiencias, hardware: CATEGORY_IDS.hardware, automatizacion: CATEGORY_IDS.automatizacion, ia: CATEGORY_IDS.ia, datos: CATEGORY_IDS.datos, software: CATEGORY_IDS.software };
const normalizeSolution = (value: Solution & { published?: boolean; coverImage?: string }): Solution => ({ ...value, categoryId: LEGACY_CATEGORY_IDS[value.categoryId] ?? value.categoryId, status: value.status ?? (value.published === false ? 'draft' : 'published'), gallery: value.gallery?.map((media, index) => ({ ...media, isCover: media.isCover ?? index === 0 })) ?? (value.coverImage ? [{ id: crypto.randomUUID(), url: value.coverImage, alt: value.name, type: 'image', order: 1, isCover: true }] : []) });
const allSolutions = (): Solution[] => read<(Solution & { published?: boolean; coverImage?: string })[]>(SOLUTIONS, seedSolutions).map(normalizeSolution);

export class MockAuthRepository implements AuthRepository {
  async requestCode(request: RequestOtpDto): Promise<OtpChallengeDto> { return { challengeId: crypto.randomUUID(), expiresAt: new Date(Date.now() + 300_000).toISOString(), maskedDestination: request.destination }; }
  async verifyCode(request: VerifyOtpDto): Promise<AuthSession> { return { authenticated: request.code === '123456', roles: request.code === '123456' ? ['admin'] : [] }; }
}
export class ApiAuthRepository implements AuthRepository { async requestCode(_request: RequestOtpDto): Promise<OtpChallengeDto> { throw new Error('TODO BACKEND PHASE'); } async verifyCode(_request: VerifyOtpDto): Promise<AuthSession> { throw new Error('TODO BACKEND PHASE'); } }
export class MockAdminCatalogRepository implements AdminCatalogRepository {
  async getSolutions(query: AdminSolutionQuery = {}): Promise<PagedResult<AdminSolutionListItem>> { let result = allSolutions(); if (query.search) result = result.filter((item) => item.name.toLocaleLowerCase().includes(query.search!.toLocaleLowerCase())); if (query.categoryId) result = result.filter((item) => item.categoryId === query.categoryId); if (query.status) result = result.filter((item) => item.status === query.status); const page = query.page ?? 1; const pageSize = query.pageSize ?? Math.max(result.length, 1); const items = result.slice((page - 1) * pageSize, page * pageSize).map((item) => ({ id: item.id, name: item.name, slug: item.slug, categoryId: item.categoryId, status: item.status, featured: item.featured, coverMedia: getSolutionCover(item) })); return { items, page, pageSize, totalItems: result.length, totalPages: Math.ceil(result.length / pageSize) }; }
  async getSolutionById(id: string): Promise<Solution | null> { return allSolutions().find((item) => item.id === id) ?? null; }
  async createSolution(input: CreateSolutionInput): Promise<Solution> { const all = allSolutions(); const item: Solution = { ...input, id: crypto.randomUUID(), slug: input.slug || slugify(input.name), order: input.order ?? all.length + 1 }; save(SOLUTIONS, [...all, item]); return item; }
  async updateSolution(id: string, input: UpdateSolutionInput): Promise<Solution> { const all = allSolutions(); const current = all.find((item) => item.id === id); if (!current) throw new Error(`Solution ${id} not found`); const item = { ...current, ...input }; save(SOLUTIONS, all.map((entry) => entry.id === id ? item : entry)); return item; }
  async deleteSolution(id: string): Promise<void> { save(SOLUTIONS, allSolutions().filter((item) => item.id !== id)); }
  async duplicateSolution(id: string): Promise<Solution> { const item = await this.getSolutionById(id); if (!item) throw new Error(`Solution ${id} not found`); const { id: _id, order: _order, publishedAt: _publishedAt, ...copy } = item; return this.createSolution({ ...copy, name: `${item.name} (copia)`, slug: `${item.slug}-copia`, status: 'draft' }); }
  async publishSolution(id: string): Promise<Solution> { return this.updateSolution(id, { status: 'published', publishedAt: new Date().toISOString() }); }
  async unpublishSolution(id: string): Promise<Solution> { return this.updateSolution(id, { status: 'draft', publishedAt: undefined }); }
  async getCategories(): Promise<ServiceCategory[]> { return read<ServiceCategory[]>(CATEGORIES, seedCategories).map((item) => ({ ...item, id: LEGACY_CATEGORY_IDS[item.id] ?? item.id })); }
  async createCategory(input: CreateCategoryInput): Promise<ServiceCategory> { const all = await this.getCategories(); const item = { ...input, id: crypto.randomUUID(), order: input.order ?? all.length + 1 }; save(CATEGORIES, [...all, item]); return item; }
  async updateCategory(id: string, input: UpdateCategoryInput): Promise<ServiceCategory> { const all = await this.getCategories(); const current = all.find((item) => item.id === id); if (!current) throw new Error(`Category ${id} not found`); const item = { ...current, ...input }; save(CATEGORIES, all.map((entry) => entry.id === id ? item : entry)); return item; }
  async deleteCategory(id: string): Promise<void> { save(CATEGORIES, (await this.getCategories()).filter((item) => item.id !== id)); }
  async reorderCategories(items: ReorderCategoryItem[]): Promise<void> { const orders = new Map(items.map((item) => [item.id, item.order])); save(CATEGORIES, (await this.getCategories()).map((item) => ({ ...item, order: orders.get(item.id) ?? item.order })).sort((a, b) => a.order - b.order)); }
}
export class ApiAdminCatalogRepository implements AdminCatalogRepository { async getSolutions(_query?: AdminSolutionQuery): Promise<PagedResult<AdminSolutionListItem>> { throw new Error('TODO BACKEND PHASE'); } async getSolutionById(_id: string): Promise<Solution | null> { throw new Error('TODO BACKEND PHASE'); } async createSolution(_input: CreateSolutionInput): Promise<Solution> { throw new Error('TODO BACKEND PHASE'); } async updateSolution(_id: string, _input: UpdateSolutionInput): Promise<Solution> { throw new Error('TODO BACKEND PHASE'); } async deleteSolution(_id: string): Promise<void> { throw new Error('TODO BACKEND PHASE'); } async duplicateSolution(_id: string): Promise<Solution> { throw new Error('TODO BACKEND PHASE'); } async publishSolution(_id: string): Promise<Solution> { throw new Error('TODO BACKEND PHASE'); } async unpublishSolution(_id: string): Promise<Solution> { throw new Error('TODO BACKEND PHASE'); } async getCategories(): Promise<ServiceCategory[]> { throw new Error('TODO BACKEND PHASE'); } async createCategory(_input: CreateCategoryInput): Promise<ServiceCategory> { throw new Error('TODO BACKEND PHASE'); } async updateCategory(_id: string, _input: UpdateCategoryInput): Promise<ServiceCategory> { throw new Error('TODO BACKEND PHASE'); } async deleteCategory(_id: string): Promise<void> { throw new Error('TODO BACKEND PHASE'); } async reorderCategories(_items: ReorderCategoryItem[]): Promise<void> { throw new Error('TODO BACKEND PHASE'); } }
export class MockMediaRepository implements MediaRepository { async createUpload(_request: CreateMediaUploadRequest): Promise<MediaUploadResultDto> { throw new Error('Mock uploads use URL.createObjectURL in the editor'); } async saveMetadata(media: SolutionMedia[]): Promise<SolutionMedia[]> { return media; } }
export class ApiMediaRepository implements MediaRepository { async createUpload(_request: CreateMediaUploadRequest): Promise<MediaUploadResultDto> { throw new Error('TODO BACKEND PHASE'); } async saveMetadata(_media: SolutionMedia[]): Promise<SolutionMedia[]> { throw new Error('TODO BACKEND PHASE'); } }
export const authRepository: AuthRepository = new MockAuthRepository(); export const adminRepository: AdminCatalogRepository = new MockAdminCatalogRepository();
