import { ArrowLeft, ArrowRight, Search, SlidersHorizontal, X } from 'lucide-react';
import { Link } from 'react-router-dom';
import { getSolutionCover } from '../../../../catalog-core/mappers';
import { useCatalog } from '../hooks/CatalogContext';
import styles from '../catalog.module.css';

export function CatalogHeader() {
  const { selection, setDrawerOpen } = useCatalog();
  return <header className={styles.header}><Link to="/" className={styles.logo} aria-label="APX, inicio">APX</Link><nav aria-label="Catálogo"><Link to="/productos">Soluciones</Link><Link to="/solicitar-propuesta">Solicitar propuesta</Link></nav><button className={styles.projectButton} onClick={() => setDrawerOpen(true)}>Mi proyecto <span>{selection.length}</span></button></header>;
}
export function CatalogHero({ query, setQuery }) { return <section className={styles.hero}><p className={styles.eyebrow}>CATÁLOGO APX · 2026</p><h1>Encuentra la tecnología<br/>que necesita tu idea.</h1><p>Explora soluciones para experiencias, operaciones y productos digitales.</p><label className={styles.search}><Search aria-hidden="true"/><span className={styles.srOnly}>Buscar soluciones</span><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Buscar soluciones..."/></label></section>; }
export function CategoryCard({ category }) { return <Link className={styles.categoryCard} to={`/productos/categoria/${category.slug}`}><div className={styles.media}><img src={category.image} alt="" loading="lazy"/></div><div><h3>{category.name}</h3><p>{category.shortDescription}</p></div><span className={styles.roundArrow}><ArrowRight/></span></Link>; }
export function SolutionCard({ solution }) { const category = useCatalog().categories.find(c => c.id === solution.categoryId); const cover = getSolutionCover(solution); return <article className={styles.solutionCard}><Link to={`/productos/${solution.slug}`} className={styles.solutionMedia}>{cover ? <img src={cover.url} alt={cover.alt || solution.name} loading="lazy"/> : <div className={styles.placeholder}><b>APX</b><span>{solution.name}</span></div>}</Link><div className={styles.solutionBody}><small>{category?.name}</small><h3><Link to={`/productos/${solution.slug}`}>{solution.name}</Link></h3><p>{solution.shortDescription}</p><Link to={`/productos/${solution.slug}`} className={styles.explore}>Explorar <ArrowRight/></Link></div></article>; }
export function SolutionGrid({ items }) { return <div className={styles.solutionGrid}>{items.map(item => <SolutionCard solution={item} key={item.id}/>)}</div>; }
export function CatalogToolbar({ sort, setSort }) { return <div className={styles.toolbar}><button><SlidersHorizontal/> Filtros</button><span>{/* category controlled by pills */}Categoría</span><label>Ordenar por <select value={sort} onChange={e => setSort(e.target.value)}><option value="featured">Destacados</option><option value="name">Nombre</option></select></label></div>; }
export function ProjectDrawer() { const { drawerOpen, setDrawerOpen, selection, solutions, remove } = useCatalog(); const selected = selection.map(i => solutions.find(s => s.id === i.solutionId)).filter(Boolean); return <><button className={`${styles.scrim} ${drawerOpen ? styles.open : ''}`} aria-label="Cerrar Mi proyecto" onClick={() => setDrawerOpen(false)}/><aside className={`${styles.drawer} ${drawerOpen ? styles.open : ''}`} aria-hidden={!drawerOpen}><div className={styles.drawerHead}><div><small>SELECCIÓN</small><h2>Mi proyecto</h2></div><button onClick={() => setDrawerOpen(false)} aria-label="Cerrar"><X/></button></div><div className={styles.drawerItems}>{selected.length ? selected.map(item => { const cover = getSolutionCover(item); return <div className={styles.projectItem} key={item.id}><div>{cover ? <img src={cover.url} alt=""/> : <span>APX</span>}</div><p><b>{item.name}</b><small>{item.shortDescription}</small></p><button onClick={() => remove(item.id)} aria-label={`Quitar ${item.name}`}><X/></button></div>; }) : <p className={styles.empty}>Agrega soluciones para construir el alcance de tu proyecto.</p>}</div><div className={styles.drawerFoot}><p><b>{selected.length}</b> {selected.length === 1 ? 'solución' : 'soluciones'}</p><Link className={styles.primary} to="/solicitar-propuesta" onClick={() => setDrawerOpen(false)}>Continuar <ArrowRight/></Link></div></aside></>; }
export function CatalogShell({ children }) { return <div className={styles.catalog}><CatalogHeader/><main>{children}</main><footer className={styles.catalogFooter}><b>APX</b><p>Tecnología diseñada alrededor de ideas reales.</p><Link to="/"><ArrowLeft/> Volver al sitio</Link></footer><ProjectDrawer/></div>; }
