// <auto-generated />
using System;
using APX.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace APX.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApxDbContext))]
    [Migration("20260816160459_CatalogApiIndexes")]
    partial class CatalogApiIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("APX.Domain.Admin.AdminUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_login_at");

                    b.Property<string>("Phone")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("phone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_admin_users_email")
                        .HasFilter("email IS NOT NULL");

                    b.HasIndex("Phone")
                        .IsUnique()
                        .HasDatabaseName("ux_admin_users_phone")
                        .HasFilter("phone IS NOT NULL");

                    b.ToTable("admin_users", null, t =>
                        {
                            t.HasCheckConstraint("ck_admin_users_destination", "email IS NOT NULL OR phone IS NOT NULL");
                        });
                });

            modelBuilder.Entity("APX.Domain.Admin.AdminUserRole", b =>
                {
                    b.Property<Guid>("AdminUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("admin_user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("AdminUserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("admin_user_roles", (string)null);
                });

            modelBuilder.Entity("APX.Domain.Admin.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("action");

                    b.Property<Guid?>("AdminUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("admin_user_id");

                    b.Property<string>("AfterJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("after_json");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("before_json");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_address");

                    b.HasKey("Id");

                    b.HasIndex("AdminUserId");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_log_entity");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("APX.Domain.Admin.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ux_roles_name");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("APX.Domain.Catalog.Modality", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("slug");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_modalities_slug");

                    b.ToTable("modalities", (string)null);
                });

            modelBuilder.Entity("APX.Domain.Catalog.ServiceCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Icon")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("icon");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("short_description");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("slug");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_service_categories_slug");

                    b.ToTable("service_categories", null, t =>
                        {
                            t.HasCheckConstraint("ck_service_categories_slug", "length(trim(slug)) > 0");

                            t.HasCheckConstraint("ck_service_categories_sort_order", "sort_order >= 0");
                        });
                });

            modelBuilder.Entity("APX.Domain.Catalog.Solution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .HasColumnType("char(3)")
                        .HasColumnName("currency");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Eyebrow")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("eyebrow");

                    b.Property<bool>("Featured")
                        .HasColumnType("boolean")
                        .HasColumnName("featured");

                    b.Property<string>("ImplementationTime")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("implementation_time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<decimal?>("PriceFrom")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price_from");

                    b.Property<string>("PriceMode")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("price_mode");

                    b.Property<decimal?>("PriceTo")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price_to");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("published_at");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("short_description");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)")
                        .HasColumnName("slug");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_solutions_slug");

                    b.HasIndex("CategoryId", "SortOrder")
                        .HasDatabaseName("ix_solutions_category_order");

                    b.HasIndex("Featured", "SortOrder")
                        .HasDatabaseName("ix_solutions_featured_order");

                    b.HasIndex("Status", "SortOrder")
                        .HasDatabaseName("ix_solutions_status_order");

                    b.ToTable("solutions", null, t =>
                        {
                            t.HasCheckConstraint("ck_solutions_currency", "currency IS NULL OR length(currency) = 3");

                            t.HasCheckConstraint("ck_solutions_slug", "length(trim(slug)) > 0");

                            t.HasCheckConstraint("ck_solutions_sort_order", "sort_order >= 0");
                        });
                });

            modelBuilder.Entity("APX.Domain.Catalog.SolutionFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)")
                        .HasColumnName("description");

                    b.Property<Guid>("SolutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("solution_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("SolutionId");

                    b.ToTable("solution_features", null, t =>
                        {
                            t.HasCheckConstraint("ck_solution_features_order", "sort_order >= 0");
                        });
                });

            modelBuilder.Entity("APX.Domain.Catalog.SolutionMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Alt")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("alt");

                    b.Property<long?>("Bytes")
                        .HasColumnType("bigint")
                        .HasColumnName("bytes");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<int?>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<bool>("IsCover")
                        .HasColumnType("boolean")
                        .HasColumnName("is_cover");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("media_type");

                    b.Property<string>("MimeType")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("mime_type");

                    b.Property<string>("PublicUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("public_url");

                    b.Property<Guid>("SolutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("solution_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("StorageKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("storage_key");

                    b.Property<int?>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id");

                    b.HasIndex("SolutionId")
                        .IsUnique()
                        .HasDatabaseName("ux_solution_media_single_cover")
                        .HasFilter("is_cover = true");

                    b.ToTable("solution_media", null, t =>
                        {
                            t.HasCheckConstraint("ck_solution_media_dimensions", "(width IS NULL OR width > 0) AND (height IS NULL OR height > 0) AND (bytes IS NULL OR bytes >= 0)");

                            t.HasCheckConstraint("ck_solution_media_order", "sort_order >= 0");
                        });
                });

            modelBuilder.Entity("APX.Domain.Catalog.SolutionModality", b =>
                {
                    b.Property<Guid>("SolutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("solution_id");

                    b.Property<Guid>("ModalityId")
                        .HasColumnType("uuid")
                        .HasColumnName("modality_id");

                    b.HasKey("SolutionId", "ModalityId");

                    b.HasIndex("ModalityId");

                    b.ToTable("solution_modalities", (string)null);
                });

            modelBuilder.Entity("APX.Domain.Catalog.SolutionRelation", b =>
                {
                    b.Property<Guid>("SolutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("solution_id");

                    b.Property<Guid>("RelatedSolutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("related_solution_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("SolutionId", "RelatedSolutionId");

                    b.HasIndex("RelatedSolutionId");

                    b.ToTable("solution_relations", null, t =>
                        {
                            t.HasCheckConstraint("ck_solution_relations_not_self", "solution_id <> related_solution_id");

                            t.HasCheckConstraint("ck_solution_relations_order", "sort_order >= 0");
                        });
                });

            modelBuilder.Entity("APX.Domain.Catalog.SolutionSeo", b =>
                {
                    b.Property<Guid>("SolutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("solution_id");

                    b.Property<string>("CanonicalUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("canonical_url");

                    b.PrimitiveCollection<string[]>("Keywords")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("keywords");

                    b.Property<string>("MetaDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("meta_description");

                    b.Property<string>("MetaTitle")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("meta_title");

                    b.Property<string>("Robots")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("robots");

                    b.HasKey("SolutionId");

                    b.ToTable("solution_seo", (string)null);
                });

            modelBuilder.Entity("APX.Domain.Catalog.SolutionTag", b =>
                {
                    b.Property<Guid>("SolutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("solution_id");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.HasKey("SolutionId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("solution_tags", (string)null);
                });

            modelBuilder.Entity("APX.Domain.Catalog.SolutionUseCase", b =>
                {
                    b.Property<Guid>("SolutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("solution_id");

                    b.Property<Guid>("UseCaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("use_case_id");

                    b.HasKey("SolutionId", "UseCaseId");

                    b.HasIndex("UseCaseId");

                    b.ToTable("solution_use_cases", (string)null);
                });

            modelBuilder.Entity("APX.Domain.Catalog.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("slug");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_tags_slug");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("APX.Domain.Catalog.UseCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("slug");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_use_cases_slug");

                    b.ToTable("use_cases", (string)null);
                });

            modelBuilder.Entity("APX.Domain.Requests.ProjectRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("ApproximateDate")
                        .HasColumnType("date")
                        .HasColumnName("approximate_date");

                    b.Property<int?>("Attendees")
                        .HasColumnType("integer")
                        .HasColumnName("attendees");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("city");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("company");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("phone");

                    b.Property<string>("ProjectType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("project_type");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_project_requests_status");

                    b.ToTable("project_requests", null, t =>
                        {
                            t.HasCheckConstraint("ck_project_requests_attendees", "attendees IS NULL OR attendees >= 0");
                        });
                });

            modelBuilder.Entity("APX.Domain.Requests.ProjectRequestItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("added_at");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<Guid>("ProjectRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_request_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid>("SolutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("solution_id");

                    b.Property<string>("SolutionNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("solution_name_snapshot");

                    b.HasKey("Id");

                    b.HasIndex("ProjectRequestId");

                    b.HasIndex("SolutionId");

                    b.ToTable("project_request_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_project_request_items_quantity", "quantity > 0");
                        });
                });

            modelBuilder.Entity("APX.Domain.Admin.AdminUserRole", b =>
                {
                    b.HasOne("APX.Domain.Admin.AdminUser", "AdminUser")
                        .WithMany("UserRoles")
                        .HasForeignKey("AdminUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APX.Domain.Admin.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AdminUser");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("APX.Domain.Admin.AuditEntry", b =>
                {
                    b.HasOne("APX.Domain.Admin.AdminUser", "AdminUser")
                        .WithMany("AuditEntries")
                        .HasForeignKey("AdminUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AdminUser");
                });

            modelBuilder.Entity("APX.Domain.Catalog.Solution", b =>
                {
                    b.HasOne("APX.Domain.Catalog.ServiceCategory", "Category")
                        .WithMany("Solutions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("APX.Domain.Catalog.SolutionFeature", b =>
                {
                    b.HasOne("APX.Domain.Catalog.Solution", "Solution")
                        .WithMany("Features")
                        .HasForeignKey("SolutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Solution");
                });

            modelBuilder.Entity("APX.Domain.Catalog.SolutionMedia", b =>
                {
                    b.HasOne("APX.Domain.Catalog.Solution", "Solution")
                        .WithMany("Media")
                        .HasForeignKey("SolutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Solution");
                });

            modelBuilder.Entity("APX.Domain.Catalog.SolutionModality", b =>
                {
                    b.HasOne("APX.Domain.Catalog.Modality", "Modality")
                        .WithMany("SolutionModalities")
                        .HasForeignKey("ModalityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APX.Domain.Catalog.Solution", "Solution")
                        .WithMany("SolutionModalities")
                        .HasForeignKey("SolutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modality");

                    b.Navigation("Solution");
                });

            modelBuilder.Entity("APX.Domain.Catalog.SolutionRelation", b =>
                {
                    b.HasOne("APX.Domain.Catalog.Solution", "RelatedSolution")
                        .WithMany("RelatedFromSolutions")
                        .HasForeignKey("RelatedSolutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APX.Domain.Catalog.Solution", "Solution")
                        .WithMany("RelatedSolutions")
                        .HasForeignKey("SolutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RelatedSolution");

                    b.Navigation("Solution");
                });

            modelBuilder.Entity("APX.Domain.Catalog.SolutionSeo", b =>
                {
                    b.HasOne("APX.Domain.Catalog.Solution", "Solution")
                        .WithOne("Seo")
                        .HasForeignKey("APX.Domain.Catalog.SolutionSeo", "SolutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Solution");
                });

            modelBuilder.Entity("APX.Domain.Catalog.SolutionTag", b =>
                {
                    b.HasOne("APX.Domain.Catalog.Solution", "Solution")
                        .WithMany("SolutionTags")
                        .HasForeignKey("SolutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APX.Domain.Catalog.Tag", "Tag")
                        .WithMany("SolutionTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Solution");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("APX.Domain.Catalog.SolutionUseCase", b =>
                {
                    b.HasOne("APX.Domain.Catalog.Solution", "Solution")
                        .WithMany("SolutionUseCases")
                        .HasForeignKey("SolutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APX.Domain.Catalog.UseCase", "UseCase")
                        .WithMany("SolutionUseCases")
                        .HasForeignKey("UseCaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Solution");

                    b.Navigation("UseCase");
                });

            modelBuilder.Entity("APX.Domain.Requests.ProjectRequestItem", b =>
                {
                    b.HasOne("APX.Domain.Requests.ProjectRequest", "ProjectRequest")
                        .WithMany("Items")
                        .HasForeignKey("ProjectRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APX.Domain.Catalog.Solution", "Solution")
                        .WithMany()
                        .HasForeignKey("SolutionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProjectRequest");

                    b.Navigation("Solution");
                });

            modelBuilder.Entity("APX.Domain.Admin.AdminUser", b =>
                {
                    b.Navigation("AuditEntries");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("APX.Domain.Admin.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("APX.Domain.Catalog.Modality", b =>
                {
                    b.Navigation("SolutionModalities");
                });

            modelBuilder.Entity("APX.Domain.Catalog.ServiceCategory", b =>
                {
                    b.Navigation("Solutions");
                });

            modelBuilder.Entity("APX.Domain.Catalog.Solution", b =>
                {
                    b.Navigation("Features");

                    b.Navigation("Media");

                    b.Navigation("RelatedFromSolutions");

                    b.Navigation("RelatedSolutions");

                    b.Navigation("Seo");

                    b.Navigation("SolutionModalities");

                    b.Navigation("SolutionTags");

                    b.Navigation("SolutionUseCases");
                });

            modelBuilder.Entity("APX.Domain.Catalog.Tag", b =>
                {
                    b.Navigation("SolutionTags");
                });

            modelBuilder.Entity("APX.Domain.Catalog.UseCase", b =>
                {
                    b.Navigation("SolutionUseCases");
                });

            modelBuilder.Entity("APX.Domain.Requests.ProjectRequest", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
