using APX.Domain.Catalog;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace APX.Infrastructure.Persistence.Configurations;

public sealed class ServiceCategoryConfiguration : IEntityTypeConfiguration<ServiceCategory>
{
    public void Configure(EntityTypeBuilder<ServiceCategory> b)
    {
        b.ToTable("service_categories", t => { t.HasCheckConstraint("ck_service_categories_sort_order", "sort_order >= 0"); t.HasCheckConstraint("ck_service_categories_slug", "length(trim(slug)) > 0"); });
        b.HasKey(x => x.Id); b.Property(x => x.Id).HasColumnName("id");
        b.Property(x => x.Name).HasColumnName("name").HasMaxLength(160).IsRequired(); b.Property(x => x.Slug).HasColumnName("slug").HasMaxLength(180).IsRequired(); b.Property(x => x.ShortDescription).HasColumnName("short_description").HasMaxLength(320).IsRequired(); b.Property(x => x.Description).HasColumnName("description"); b.Property(x => x.Icon).HasColumnName("icon").HasMaxLength(160); b.Property(x => x.ImageUrl).HasColumnName("image_url").HasMaxLength(1000); b.Property(x => x.SortOrder).HasColumnName("sort_order"); b.Property(x => x.IsActive).HasColumnName("is_active"); b.Property(x => x.CreatedAt).HasColumnName("created_at").HasColumnType("timestamptz"); b.Property(x => x.UpdatedAt).HasColumnName("updated_at").HasColumnType("timestamptz"); b.Property(x => x.Version).HasColumnName("xmin").IsRowVersion();
        b.HasIndex(x => x.Slug).IsUnique().HasDatabaseName("ux_service_categories_slug");
    }
}

public sealed class SolutionConfiguration : IEntityTypeConfiguration<Solution>
{
    public void Configure(EntityTypeBuilder<Solution> b)
    {
        b.ToTable("solutions", t => { t.HasCheckConstraint("ck_solutions_sort_order", "sort_order >= 0"); t.HasCheckConstraint("ck_solutions_slug", "length(trim(slug)) > 0"); t.HasCheckConstraint("ck_solutions_currency", "currency IS NULL OR length(currency) = 3"); });
        b.HasKey(x => x.Id); b.Property(x => x.Id).HasColumnName("id"); b.Property(x => x.CategoryId).HasColumnName("category_id"); b.Property(x => x.Name).HasColumnName("name").HasMaxLength(200).IsRequired(); b.Property(x => x.Slug).HasColumnName("slug").HasMaxLength(220).IsRequired(); b.Property(x => x.Eyebrow).HasColumnName("eyebrow").HasMaxLength(120); b.Property(x => x.ShortDescription).HasColumnName("short_description").HasMaxLength(400).IsRequired(); b.Property(x => x.Description).HasColumnName("description").IsRequired();
        b.Property(x => x.PriceMode).HasColumnName("price_mode").HasMaxLength(24).HasConversion(new ValueConverter<PriceMode, string>(v => v.ToContract(), v => CatalogEnumMappings.ParsePriceMode(v))); b.Property(x => x.PriceFrom).HasColumnName("price_from").HasPrecision(18, 2); b.Property(x => x.PriceTo).HasColumnName("price_to").HasPrecision(18, 2); b.Property(x => x.Currency).HasColumnName("currency").HasColumnType("char(3)"); b.Property(x => x.Status).HasColumnName("status").HasMaxLength(20).HasConversion(new ValueConverter<SolutionStatus, string>(v => v.ToContract(), v => CatalogEnumMappings.ParseSolutionStatus(v))); b.Property(x => x.Featured).HasColumnName("featured"); b.Property(x => x.ImplementationTime).HasColumnName("implementation_time").HasMaxLength(120); b.Property(x => x.SortOrder).HasColumnName("sort_order"); b.Property(x => x.PublishedAt).HasColumnName("published_at").HasColumnType("timestamptz"); b.Property(x => x.CreatedAt).HasColumnName("created_at").HasColumnType("timestamptz"); b.Property(x => x.UpdatedAt).HasColumnName("updated_at").HasColumnType("timestamptz"); b.Property(x => x.DeletedAt).HasColumnName("deleted_at").HasColumnType("timestamptz"); b.Property(x => x.Version).HasColumnName("xmin").IsRowVersion();
        b.HasIndex(x => x.Slug).IsUnique().HasDatabaseName("ux_solutions_slug"); b.HasIndex(x => new { x.CategoryId, x.SortOrder }).HasDatabaseName("ix_solutions_category_order"); b.HasIndex(x => new { x.Status, x.SortOrder }).HasDatabaseName("ix_solutions_status_order"); b.HasIndex(x => new { x.Featured, x.SortOrder }).HasDatabaseName("ix_solutions_featured_order"); b.HasOne(x => x.Category).WithMany(x => x.Solutions).HasForeignKey(x => x.CategoryId).OnDelete(DeleteBehavior.Restrict);
    }
}

public sealed class SolutionMediaConfiguration : IEntityTypeConfiguration<SolutionMedia>
{
    public void Configure(EntityTypeBuilder<SolutionMedia> b)
    {
        b.ToTable("solution_media", t => { t.HasCheckConstraint("ck_solution_media_dimensions", "(width IS NULL OR width > 0) AND (height IS NULL OR height > 0) AND (bytes IS NULL OR bytes >= 0)"); t.HasCheckConstraint("ck_solution_media_order", "sort_order >= 0"); });
        b.HasKey(x => x.Id); b.Property(x => x.Id).HasColumnName("id"); b.Property(x => x.SolutionId).HasColumnName("solution_id"); b.Property(x => x.StorageKey).HasColumnName("storage_key").HasMaxLength(500); b.Property(x => x.PublicUrl).HasColumnName("public_url").HasMaxLength(1000).IsRequired(); b.Property(x => x.Alt).HasColumnName("alt").HasMaxLength(300).IsRequired(); b.Property(x => x.MediaType).HasColumnName("media_type").HasMaxLength(20).HasConversion(new ValueConverter<MediaType, string>(v => v.ToContract(), v => CatalogEnumMappings.ParseMediaType(v))); b.Property(x => x.MimeType).HasColumnName("mime_type").HasMaxLength(120); b.Property(x => x.Width).HasColumnName("width"); b.Property(x => x.Height).HasColumnName("height"); b.Property(x => x.Bytes).HasColumnName("bytes"); b.Property(x => x.SortOrder).HasColumnName("sort_order"); b.Property(x => x.IsCover).HasColumnName("is_cover"); b.Property(x => x.CreatedAt).HasColumnName("created_at").HasColumnType("timestamptz");
        b.HasOne(x => x.Solution).WithMany(x => x.Media).HasForeignKey(x => x.SolutionId).OnDelete(DeleteBehavior.Cascade); b.HasIndex(x => x.SolutionId).IsUnique().HasFilter("is_cover = true").HasDatabaseName("ux_solution_media_single_cover");
    }
}

public sealed class SolutionFeatureConfiguration : IEntityTypeConfiguration<SolutionFeature>
{
    public void Configure(EntityTypeBuilder<SolutionFeature> b) { b.ToTable("solution_features", t => t.HasCheckConstraint("ck_solution_features_order", "sort_order >= 0")); b.HasKey(x => x.Id); b.Property(x => x.Id).HasColumnName("id"); b.Property(x => x.SolutionId).HasColumnName("solution_id"); b.Property(x => x.Title).HasColumnName("title").HasMaxLength(220).IsRequired(); b.Property(x => x.Description).HasColumnName("description").HasMaxLength(800); b.Property(x => x.SortOrder).HasColumnName("sort_order"); b.HasOne(x => x.Solution).WithMany(x => x.Features).HasForeignKey(x => x.SolutionId).OnDelete(DeleteBehavior.Cascade); }
}

public sealed class TagConfiguration : IEntityTypeConfiguration<Tag> { public void Configure(EntityTypeBuilder<Tag> b) { ConfigureTaxonomy(b, "tags", x => x.Id, x => x.Name, x => x.Slug, x => x.IsActive); } internal static void ConfigureTaxonomy<TEntity>(EntityTypeBuilder<TEntity> b, string table, System.Linq.Expressions.Expression<Func<TEntity, object?>> id, System.Linq.Expressions.Expression<Func<TEntity, object?>> name, System.Linq.Expressions.Expression<Func<TEntity, object?>> slug, System.Linq.Expressions.Expression<Func<TEntity, object?>> active) where TEntity : class { b.ToTable(table); b.HasKey(id); b.Property(id).HasColumnName("id"); b.Property(name).HasColumnName("name").HasMaxLength(160).IsRequired(); b.Property(slug).HasColumnName("slug").HasMaxLength(180).IsRequired(); b.Property(active).HasColumnName("is_active"); b.HasIndex(slug).IsUnique().HasDatabaseName($"ux_{table}_slug"); } }
public sealed class UseCaseConfiguration : IEntityTypeConfiguration<UseCase> { public void Configure(EntityTypeBuilder<UseCase> b) { TagConfiguration.ConfigureTaxonomy(b, "use_cases", x => x.Id, x => x.Name, x => x.Slug, x => x.IsActive); b.Property(x => x.SortOrder).HasColumnName("sort_order"); } }
public sealed class ModalityConfiguration : IEntityTypeConfiguration<Modality> { public void Configure(EntityTypeBuilder<Modality> b) { TagConfiguration.ConfigureTaxonomy(b, "modalities", x => x.Id, x => x.Name, x => x.Slug, x => x.IsActive); b.Property(x => x.SortOrder).HasColumnName("sort_order"); } }
public sealed class SolutionTagConfiguration : IEntityTypeConfiguration<SolutionTag> { public void Configure(EntityTypeBuilder<SolutionTag> b) { b.ToTable("solution_tags"); b.HasKey(x => new { x.SolutionId, x.TagId }); b.Property(x => x.SolutionId).HasColumnName("solution_id"); b.Property(x => x.TagId).HasColumnName("tag_id"); b.HasOne(x => x.Solution).WithMany(x => x.SolutionTags).HasForeignKey(x => x.SolutionId).OnDelete(DeleteBehavior.Cascade); b.HasOne(x => x.Tag).WithMany(x => x.SolutionTags).HasForeignKey(x => x.TagId).OnDelete(DeleteBehavior.Restrict); } }
public sealed class SolutionUseCaseConfiguration : IEntityTypeConfiguration<SolutionUseCase> { public void Configure(EntityTypeBuilder<SolutionUseCase> b) { b.ToTable("solution_use_cases"); b.HasKey(x => new { x.SolutionId, x.UseCaseId }); b.Property(x => x.SolutionId).HasColumnName("solution_id"); b.Property(x => x.UseCaseId).HasColumnName("use_case_id"); b.HasOne(x => x.Solution).WithMany(x => x.SolutionUseCases).HasForeignKey(x => x.SolutionId).OnDelete(DeleteBehavior.Cascade); b.HasOne(x => x.UseCase).WithMany(x => x.SolutionUseCases).HasForeignKey(x => x.UseCaseId).OnDelete(DeleteBehavior.Restrict); } }
public sealed class SolutionModalityConfiguration : IEntityTypeConfiguration<SolutionModality> { public void Configure(EntityTypeBuilder<SolutionModality> b) { b.ToTable("solution_modalities"); b.HasKey(x => new { x.SolutionId, x.ModalityId }); b.Property(x => x.SolutionId).HasColumnName("solution_id"); b.Property(x => x.ModalityId).HasColumnName("modality_id"); b.HasOne(x => x.Solution).WithMany(x => x.SolutionModalities).HasForeignKey(x => x.SolutionId).OnDelete(DeleteBehavior.Cascade); b.HasOne(x => x.Modality).WithMany(x => x.SolutionModalities).HasForeignKey(x => x.ModalityId).OnDelete(DeleteBehavior.Restrict); } }
public sealed class SolutionRelationConfiguration : IEntityTypeConfiguration<SolutionRelation> { public void Configure(EntityTypeBuilder<SolutionRelation> b) { b.ToTable("solution_relations", t => { t.HasCheckConstraint("ck_solution_relations_not_self", "solution_id <> related_solution_id"); t.HasCheckConstraint("ck_solution_relations_order", "sort_order >= 0"); }); b.HasKey(x => new { x.SolutionId, x.RelatedSolutionId }); b.Property(x => x.SolutionId).HasColumnName("solution_id"); b.Property(x => x.RelatedSolutionId).HasColumnName("related_solution_id"); b.Property(x => x.SortOrder).HasColumnName("sort_order"); b.HasOne(x => x.Solution).WithMany(x => x.RelatedSolutions).HasForeignKey(x => x.SolutionId).OnDelete(DeleteBehavior.Cascade); b.HasOne(x => x.RelatedSolution).WithMany(x => x.RelatedFromSolutions).HasForeignKey(x => x.RelatedSolutionId).OnDelete(DeleteBehavior.Cascade); } }
public sealed class SolutionSeoConfiguration : IEntityTypeConfiguration<SolutionSeo> { public void Configure(EntityTypeBuilder<SolutionSeo> b) { b.ToTable("solution_seo"); b.HasKey(x => x.SolutionId); b.Property(x => x.SolutionId).HasColumnName("solution_id"); b.Property(x => x.MetaTitle).HasColumnName("meta_title").HasMaxLength(240); b.Property(x => x.MetaDescription).HasColumnName("meta_description").HasMaxLength(500); b.Property(x => x.CanonicalUrl).HasColumnName("canonical_url").HasMaxLength(1000); b.Property(x => x.Robots).HasColumnName("robots").HasMaxLength(100); b.Property(x => x.Keywords).HasColumnName("keywords").HasColumnType("text[]"); b.HasOne(x => x.Solution).WithOne(x => x.Seo).HasForeignKey<SolutionSeo>(x => x.SolutionId).OnDelete(DeleteBehavior.Cascade); } }
