using System.Data;
using APX.Application.Dashboard;
using APX.Domain.Requests;
using APX.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;

namespace APX.Infrastructure.Dashboard;

public sealed class EfDashboardRepository(ApxDbContext db) : IDashboardRepository
{
    public async Task<DashboardDto> GetAsync(DateTimeOffset from,DateTimeOffset to,DateTimeOffset now,int attentionHours,CancellationToken ct)
    {
        var ranged=db.ProjectRequests.AsNoTracking().Where(x=>x.CreatedAt>=from&&x.CreatedAt<to);
        var statusCounts=await ranged.GroupBy(x=>x.Status).Select(x=>new{x.Key,Count=x.Count()}).ToDictionaryAsync(x=>x.Key,x=>x.Count,ct);
        int C(ProjectRequestStatus status)=>statusCounts.GetValueOrDefault(status);
        var total=statusCounts.Values.Sum();var pipelineTotal=total-C(ProjectRequestStatus.Archived);
        var pipeline=new[]{ProjectRequestStatus.New,ProjectRequestStatus.InReview,ProjectRequestStatus.Contacted,ProjectRequestStatus.Qualified,ProjectRequestStatus.Won,ProjectRequestStatus.Lost}.Select(status=>new DashboardPipelineItemDto(status.ToString(),C(status),pipelineTotal==0?0:C(status)*100d/pipelineTotal)).ToArray();
        var qualified=C(ProjectRequestStatus.Qualified)+C(ProjectRequestStatus.Won)+C(ProjectRequestStatus.Lost);var outcomes=C(ProjectRequestStatus.Won)+C(ProjectRequestStatus.Lost);
        var contacted=ranged.Where(x=>x.LastContactedAt!=null);var average=await contacted.Select(x=>(double?)(x.LastContactedAt!.Value-x.CreatedAt).TotalMinutes).AverageAsync(ct);var median=await MedianAsync(from,to,ct);
        var backlogQuery=db.ProjectRequests.AsNoTracking().Where(x=>(x.Status==ProjectRequestStatus.New||x.Status==ProjectRequestStatus.InReview)&&x.LastContactedAt==null);var backlogCount=await backlogQuery.CountAsync(ct);var oldest=await backlogQuery.MinAsync(x=>(DateTimeOffset?)x.CreatedAt,ct);
        var groupedTrend=await ranged.GroupBy(x=>x.CreatedAt.Date).Select(x=>new{x.Key,Count=x.Count()}).OrderBy(x=>x.Key).ToListAsync(ct);var trend=FillTrend(from,to,groupedTrend.Select(x=>(DateOnly.FromDateTime(x.Key),x.Count)).ToDictionary()).ToArray();
        var duration=to-from;var previousFrom=from-duration;var previous=await db.ProjectRequests.AsNoTracking().Where(x=>x.CreatedAt>=previousFrom&&x.CreatedAt<from).GroupBy(_=>1).Select(x=>new{Total=x.Count(),Won=x.Count(r=>r.Status==ProjectRequestStatus.Won)}).SingleOrDefaultAsync(ct);var previousTotal=previous?.Total??0;var previousWon=previous?.Won??0;
        var topSolutions=await TopSolutionsAsync(from,to,ct);var topCategories=await TopCategoriesAsync(from,to,ct);
        var cityRows=await ranged.GroupBy(x=>x.City.ToLower()).Select(x=>new{City=x.Min(v=>v.City),Count=x.Count()}).OrderByDescending(x=>x.Count).ThenBy(x=>x.City).Take(5).ToListAsync(ct);var topCities=cityRows.Select(x=>new DashboardTopCityDto(x.City??string.Empty,x.Count)).ToArray();
        var recent=await ranged.OrderByDescending(x=>x.CreatedAt).Take(8).Select(x=>new DashboardRequestListItemDto(x.Id,x.RequestNumber,x.Name,x.Company,x.City,x.Status.ToString(),x.CreatedAt)).ToListAsync(ct);
        var cutoff=now.AddHours(-attentionHours);var attentionQuery=backlogQuery.Where(x=>x.CreatedAt<cutoff);var attentionCount=await attentionQuery.CountAsync(ct);var attention=await attentionQuery.OrderBy(x=>x.CreatedAt).Take(5).Select(x=>new DashboardRequestListItemDto(x.Id,x.RequestNumber,x.Name,x.Company,x.City,x.Status.ToString(),x.CreatedAt)).ToListAsync(ct);
        return new(new(from,to,attentionHours),new(total,C(ProjectRequestStatus.New),C(ProjectRequestStatus.InReview),C(ProjectRequestStatus.Contacted),C(ProjectRequestStatus.Qualified),C(ProjectRequestStatus.Won),C(ProjectRequestStatus.Lost),C(ProjectRequestStatus.Archived)),pipeline,new(pipelineTotal==0?0:qualified*100d/pipelineTotal,outcomes==0?0:C(ProjectRequestStatus.Won)*100d/outcomes,outcomes==0?0:C(ProjectRequestStatus.Lost)*100d/outcomes),new(average,median),new(backlogCount,oldest is null?null:(now-oldest.Value).TotalMinutes),trend,new(previousTotal,previousWon,Change(total,previousTotal),Change(C(ProjectRequestStatus.Won),previousWon)),topSolutions,topCategories,topCities,recent,new(attentionCount,attention));
    }
    private async Task<double?> MedianAsync(DateTimeOffset from,DateTimeOffset to,CancellationToken ct){var connection=db.Database.GetDbConnection();var close=connection.State!=ConnectionState.Open;if(close)await connection.OpenAsync(ct);try{await using var command=connection.CreateCommand();command.CommandText="SELECT percentile_cont(0.5) WITHIN GROUP (ORDER BY EXTRACT(EPOCH FROM (last_contacted_at-created_at))/60.0) FROM project_requests WHERE created_at>=@from AND created_at<@to AND last_contacted_at IS NOT NULL";var p1=command.CreateParameter();p1.ParameterName="from";p1.Value=from;command.Parameters.Add(p1);var p2=command.CreateParameter();p2.ParameterName="to";p2.Value=to;command.Parameters.Add(p2);var value=await command.ExecuteScalarAsync(ct);return value is null or DBNull?null:Convert.ToDouble(value);}finally{if(close)await connection.CloseAsync();}}
    private async Task<IReadOnlyList<DashboardTopSolutionDto>> TopSolutionsAsync(DateTimeOffset from,DateTimeOffset to,CancellationToken ct){var rows=new List<DashboardTopSolutionDto>();var connection=db.Database.GetDbConnection();var close=connection.State!=ConnectionState.Open;if(close)await connection.OpenAsync(ct);try{await using var command=connection.CreateCommand();command.CommandText="SELECT pri.solution_name,pri.solution_slug,pri.category_name,COUNT(DISTINCT pri.project_request_id)::int FROM project_request_items pri JOIN project_requests pr ON pr.id=pri.project_request_id WHERE pr.created_at>=@from AND pr.created_at<@to GROUP BY pri.solution_name,pri.solution_slug,pri.category_name ORDER BY COUNT(DISTINCT pri.project_request_id) DESC,pri.solution_name ASC LIMIT 5";AddRange(command,from,to);await using var reader=await command.ExecuteReaderAsync(ct);while(await reader.ReadAsync(ct))rows.Add(new(reader.GetString(0),reader.GetString(1),reader.GetString(2),reader.GetInt32(3)));return rows;}finally{if(close)await connection.CloseAsync();}}
    private async Task<IReadOnlyList<DashboardTopCategoryDto>> TopCategoriesAsync(DateTimeOffset from,DateTimeOffset to,CancellationToken ct){var rows=new List<DashboardTopCategoryDto>();var connection=db.Database.GetDbConnection();var close=connection.State!=ConnectionState.Open;if(close)await connection.OpenAsync(ct);try{await using var command=connection.CreateCommand();command.CommandText="SELECT pri.category_name,COUNT(DISTINCT pri.project_request_id)::int FROM project_request_items pri JOIN project_requests pr ON pr.id=pri.project_request_id WHERE pr.created_at>=@from AND pr.created_at<@to GROUP BY pri.category_name ORDER BY COUNT(DISTINCT pri.project_request_id) DESC,pri.category_name ASC LIMIT 5";AddRange(command,from,to);await using var reader=await command.ExecuteReaderAsync(ct);while(await reader.ReadAsync(ct))rows.Add(new(reader.GetString(0),reader.GetInt32(1)));return rows;}finally{if(close)await connection.CloseAsync();}}
    private static void AddRange(System.Data.Common.DbCommand command,DateTimeOffset from,DateTimeOffset to){var p1=command.CreateParameter();p1.ParameterName="from";p1.Value=from;command.Parameters.Add(p1);var p2=command.CreateParameter();p2.ParameterName="to";p2.Value=to;command.Parameters.Add(p2);}
    private static IEnumerable<DashboardTrendItemDto> FillTrend(DateTimeOffset from,DateTimeOffset to,IReadOnlyDictionary<DateOnly,int> values){for(var date=DateOnly.FromDateTime(from.UtcDateTime);date<=DateOnly.FromDateTime(to.AddTicks(-1).UtcDateTime);date=date.AddDays(1))yield return new(date,values.GetValueOrDefault(date));}
    private static double? Change(int current,int previous)=>previous==0?null:(current-previous)*100d/previous;
}
