import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { ApiAdminCatalogRepository, ApiAuthRepository, ApiMediaRepository } from '../repositories';
import { AdminApiError } from './apiClient';

const json = (body: unknown, status = 200, headers: Record<string, string> = {}) => new Response(status === 204 ? null : JSON.stringify(body), { status, headers: { 'Content-Type': 'application/json', ...headers } });
const session = { authenticated: true, userId: '00000000-0000-4000-8000-000000000001', displayName: 'Admin', email: 'a@example.test', roles: ['Admin'], permissions: ['admin.read'], expiresAt: new Date().toISOString() };

describe('admin API repositories', () => {
  const fetchMock = vi.fn<typeof fetch>();
  beforeEach(() => { fetchMock.mockReset(); vi.stubGlobal('fetch', fetchMock); });
  afterEach(() => { vi.unstubAllGlobals(); vi.restoreAllMocks(); });

  it('requests OTP and always includes credentials', async () => { fetchMock.mockResolvedValue(json({ challengeId: '00000000-0000-4000-8000-000000000002', expiresAt: '', maskedDestination: 'a***@example.test' }, 202)); await new ApiAuthRepository().requestCode({ channel: 'email', destination: 'a@example.test' }); expect(fetchMock).toHaveBeenCalledWith(expect.stringContaining('/api/v1/auth/otp/request'), expect.objectContaining({ credentials: 'include', method: 'POST' })); });
  it('verifies OTP and refreshes auth me', async () => { fetchMock.mockResolvedValueOnce(json(session)).mockResolvedValueOnce(json(session)); const result = await new ApiAuthRepository().verifyCode({ challengeId: '00000000-0000-4000-8000-000000000002', code: '123456' }); expect(result.userId).toBe(session.userId); expect(fetchMock.mock.calls[1]?.[0]).toContain('/api/v1/auth/me'); });
  it('maps auth me 401 to anonymous and sends real logout', async () => { const auth = new ApiAuthRepository(); fetchMock.mockResolvedValueOnce(json({ code: 'unauthorized' }, 401)); await expect(auth.getCurrentSession()).resolves.toBeNull(); fetchMock.mockResolvedValueOnce(json(null, 204)); await auth.logout(); expect(fetchMock.mock.calls[1]?.[1]).toEqual(expect.objectContaining({ method: 'POST', credentials: 'include' })); });
  it('preserves 403 and ProblemDetails field errors', async () => { fetchMock.mockResolvedValue(json({ code: 'forbidden', detail: 'Denied', traceId: 'trace', errors: { slug: ['Used'] } }, 403)); await expect(new ApiAdminCatalogRepository().getCategories()).rejects.toMatchObject<Partial<AdminApiError>>({ status: 403, code: 'forbidden', detail: 'Denied', traceId: 'trace', fieldErrors: { slug: ['Used'] } }); });
  it('uses server-side solution query and maps create/update payloads', async () => { const repository = new ApiAdminCatalogRepository(); fetchMock.mockResolvedValueOnce(json({ items: [], page: 2, pageSize: 12, totalItems: 15, totalPages: 2 })); await repository.getSolutions({ search: 'AI', categoryId: '00000000-0000-4000-8000-000000000003', page: 2, status: 'draft' }); expect(fetchMock.mock.calls[0]?.[0]).toContain('search=AI'); expect(fetchMock.mock.calls[0]?.[0]).toContain('page=2'); const solution = { id: '00000000-0000-4000-8000-000000000004', name: 'Test', slug: 'test', categoryId: '00000000-0000-4000-8000-000000000003', shortDescription: 'Short', description: 'Long', gallery: [], features: [], useCases: [], tags: [], modalities: [], priceMode: 'quote' as const, featured: false, status: 'draft' as const, order: 1, rowVersion: '7' }; fetchMock.mockResolvedValueOnce(json(solution, 201)); await repository.createSolution(solution); fetchMock.mockResolvedValueOnce(json(solution)); await repository.updateSolution(solution.id, solution); const updateBody = JSON.parse(fetchMock.mock.calls[2]?.[1]?.body as string); expect(updateBody.rowVersion).toBe('7'); expect(updateBody.media).toEqual([]); });
  it('surfaces optimistic concurrency conflicts', async () => { fetchMock.mockResolvedValue(json({ code: 'concurrency_conflict', detail: 'Changed' }, 409)); await expect(new ApiAdminCatalogRepository().updateSolution('id', { rowVersion: '1' } as never)).rejects.toMatchObject({ status: 409, code: 'concurrency_conflict' }); });
  it('uploads multipart, sets cover, updates and deletes media', async () => { const media = new ApiMediaRepository(); const dto = { id: 'm', url: 'https://x', alt: 'A', type: 'image' as const, order: 0, isCover: true }; fetchMock.mockResolvedValueOnce(json(dto, 201)); await media.createUpload({ solutionId: 's', file: new File(['png'], 'x.png', { type: 'image/png' }), alt: 'A', isCover: true }); const body = fetchMock.mock.calls[0]?.[1]?.body; expect(body).toBeInstanceOf(FormData); expect((body as FormData).get('file')).toBeInstanceOf(File); fetchMock.mockResolvedValueOnce(json(dto)); await media.setCover('s', 'm'); expect(fetchMock.mock.calls[1]?.[0]).toContain('/cover'); fetchMock.mockResolvedValueOnce(json(dto)); await media.updateMetadata('s', 'm', { alt: 'B', order: 2 }); fetchMock.mockResolvedValueOnce(json(null, 204)); await media.delete('s', 'm'); expect(fetchMock.mock.calls[3]?.[1]).toEqual(expect.objectContaining({ method: 'DELETE', credentials: 'include' })); });
});
