import { useEffect, useState } from 'react';
import { CatalogError, CatalogHero, CatalogLoading, CatalogShell, CatalogToolbar, CategoryCard, Pagination, SolutionGrid } from '../components/CatalogComponents';
import { useCatalog } from '../hooks/CatalogContext';
import styles from '../catalog.module.css';

export default function CatalogPage() {
  const { categories, loading: categoriesLoading, error: categoriesError, retryCategories, loadSolutions } = useCatalog();
  const [query, setQuery] = useState(''); const [debouncedQuery, setDebouncedQuery] = useState(''); const [active, setActive] = useState('all'); const [sort, setSort] = useState('featured'); const [page, setPage] = useState(1);
  const [result, setResult] = useState({ items: [], page: 1, pageSize: 12, totalItems: 0, totalPages: 0 }); const [loading, setLoading] = useState(true); const [error, setError] = useState(null); const [reload, setReload] = useState(0);
  useEffect(() => { const timer = window.setTimeout(() => { setDebouncedQuery(query.trim()); setPage(1); setLoading(true); setError(null); }, 320); return () => window.clearTimeout(timer); }, [query]);
  useEffect(() => { const controller = new AbortController(); loadSolutions({ search: debouncedQuery || undefined, categorySlug: active === 'all' ? undefined : active, sort, page, pageSize: 12 }, controller.signal).then(setResult).catch((reason) => { if (reason?.name !== 'AbortError') setError(reason); }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); return () => controller.abort(); }, [active, debouncedQuery, loadSolutions, page, reload, sort]);
  const changeCategory = (value) => { setActive(value); setPage(1); setLoading(true); setError(null); }; const changeSort = (value) => { setSort(value); setPage(1); setLoading(true); setError(null); }; const changePage = (value) => { setPage(value); setLoading(true); setError(null); }; const retry = () => { setLoading(true); setError(null); setReload((value) => value + 1); };
  return <CatalogShell><CatalogHero query={query} setQuery={setQuery}/><section className={styles.section}><div className={styles.sectionTitle}><p>DESCUBRE POR ÁREA</p><h2>Explora por categoría</h2></div>{categoriesError ? <CatalogError message="No pudimos cargar las categorías." onRetry={() => retryCategories().catch(() => {})}/> : categoriesLoading ? <CatalogLoading cards={6}/> : <><div className={styles.pills} role="group" aria-label="Filtrar por categoría"><button className={active === 'all' ? styles.active : ''} onClick={() => changeCategory('all')}>Todos</button>{categories.map(c => <button className={active === c.slug ? styles.active : ''} onClick={() => changeCategory(c.slug)} key={c.id}>{c.name}</button>)}</div><div className={styles.categoryRail}>{categories.map(c => <CategoryCard category={c} key={c.id}/>)}</div></>}</section><section className={styles.section}><div className={styles.sectionTitle}><p>PORTAFOLIO</p><h2>Todas las soluciones</h2></div><CatalogToolbar sort={sort} setSort={changeSort}/>{error ? <CatalogError message="No pudimos cargar las soluciones." onRetry={retry}/> : loading ? <CatalogLoading cards={8}/> : <><SolutionGrid items={result.items}/>{!result.items.length && <p className={styles.noResults}>No encontramos soluciones con esos criterios.</p>}<Pagination page={result.page} totalPages={result.totalPages} onChange={changePage}/></>}</section></CatalogShell>;
}
