import { useState } from 'react';
import { ArrowLeft, ArrowRight, Check } from 'lucide-react';
import { Link } from 'react-router-dom';
import { mapCreateProjectRequest } from '../../../../catalog-core/mappers';
import { CatalogShell } from '../components/CatalogComponents';
import { useCatalog } from '../hooks/CatalogContext';
import { projectRequestRepository } from '../repositories/catalogRepositories';
import styles from '../catalog.module.css';

const initial = { name: '', company: '', email: '', phone: '', projectType: '', city: '', approximateDate: '', attendees: '', message: '' };
export default function ProposalPage() {
  const { selection, solutions, clearProject } = useCatalog(); const [step, setStep] = useState(1); const [form, setForm] = useState(initial); const [sent, setSent] = useState(false);
  const update = (event) => setForm({ ...form, [event.target.name]: event.target.value });
  const submit = async (event) => { event.preventDefault(); if (step < 3) { setStep(step + 1); return; } const request = mapCreateProjectRequest({ ...form, approximateDate: form.approximateDate || null, attendees: form.attendees ? Number(form.attendees) : null, selections: selection }); await projectRequestRepository.create(request); clearProject(); setSent(true); };
  if (sent) return <CatalogShell><section className={styles.success}><span><Check/></span><p>SOLICITUD REGISTRADA</p><h1>Gracias. Construyamos algo memorable.</h1><p>Esta es una confirmación de demostración; todavía no se ha enviado información.</p><Link to="/productos">Volver al catálogo</Link></section></CatalogShell>;
  const selected = selection.map((item) => solutions.find((solution) => solution.id === item.solutionId)).filter(Boolean);
  return <CatalogShell><section className={styles.formPage}><div className={styles.formIntro}><p className={styles.eyebrow}>PROPUESTA APX</p><h1>Cuéntanos sobre<br/>tu proyecto.</h1><p>Tomaremos tus objetivos y las soluciones elegidas como punto de partida.</p></div><form onSubmit={submit}><ol className={styles.steps}><li className={step >= 1 ? styles.done : ''}>1 <span>Información</span></li><li className={step >= 2 ? styles.done : ''}>2 <span>Proyecto</span></li><li className={step >= 3 ? styles.done : ''}>3 <span>Resumen</span></li></ol>{step === 1 && <fieldset><legend>Información de contacto</legend><label>Nombre<input required name="name" value={form.name} onChange={update}/></label><label>Empresa<input required name="company" value={form.company} onChange={update}/></label><label>Email<input required type="email" name="email" value={form.email} onChange={update}/></label><label>Teléfono<input required name="phone" value={form.phone} onChange={update}/></label></fieldset>}{step === 2 && <fieldset><legend>Sobre el proyecto</legend><label>Tipo de proyecto<select required name="projectType" value={form.projectType} onChange={update}><option value="">Selecciona</option><option>Evento o activación</option><option>Solución empresarial</option><option>Producto digital</option></select></label><label>Ciudad<input required name="city" value={form.city} onChange={update}/></label><label>Fecha aproximada<input type="date" name="approximateDate" value={form.approximateDate} onChange={update}/></label><label>Asistentes<input type="number" min="0" name="attendees" value={form.attendees} onChange={update}/></label><label className={styles.full}>Mensaje<textarea name="message" value={form.message} onChange={update}/></label></fieldset>}{step === 3 && <div className={styles.summary}><h2>Resumen</h2><p><b>{form.name}</b> · {form.company}</p>{selected.length ? <div>{selected.map((solution) => <article key={solution.id}><span>APX</span><p><b>{solution.name}</b><small>{solution.shortDescription}</small></p></article>)}</div> : <p>No agregaste soluciones; podemos ayudarte a elegirlas.</p>}</div>}<div className={styles.formActions}>{step > 1 && <button type="button" onClick={() => setStep(step - 1)}><ArrowLeft/> Atrás</button>}<button className={styles.primary}>{step === 3 ? 'Solicitar propuesta' : 'Continuar'} <ArrowRight/></button></div></form></section></CatalogShell>;
}
