import { useEffect, useState } from 'react';
import { ArrowRight, Check } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import { getSolutionCover } from '../../../../catalog-core/mappers';
import { CatalogError, CatalogLoading, CatalogShell, SolutionGrid } from '../components/CatalogComponents';
import { useCatalog } from '../hooks/CatalogContext';
import styles from '../catalog.module.css';

export default function SolutionPage() {
  const { slug } = useParams(); const { categories, loadSolution, loadSolutions, selection, add } = useCatalog();
  const [solution, setSolution] = useState(null); const [related, setRelated] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(null); const [notFound, setNotFound] = useState(false); const [reload, setReload] = useState(0);
  useEffect(() => { const controller = new AbortController(); loadSolution(slug, controller.signal).then((item) => { if (!item) { setNotFound(true); return; } setSolution(item); }).catch((reason) => { if (reason?.name !== 'AbortError') setError(reason); }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); return () => controller.abort(); }, [loadSolution, reload, slug]);
  const category = categories.find((item) => item.id === solution?.categoryId);
  useEffect(() => { if (!solution || !category) return undefined; const controller = new AbortController(); loadSolutions({ categorySlug: category.slug, page: 1, pageSize: 100, sort: 'order' }, controller.signal).then((result) => { const explicit = solution.relatedSolutionIds?.length ? result.items.filter((item) => solution.relatedSolutionIds.includes(item.id)) : result.items.filter((item) => item.id !== solution.id).slice(0, 4); setRelated(explicit); }).catch(() => {}); return () => controller.abort(); }, [category, loadSolutions, solution]);
  if (loading) return <CatalogShell><section className={styles.section}><CatalogLoading cards={6}/></section></CatalogShell>;
  if (notFound) return <CatalogShell><div className={styles.notFound}><h1>Solución no encontrada</h1><Link to="/productos">Volver al catálogo</Link></div></CatalogShell>;
  if (error || !solution) return <CatalogShell><div className={styles.notFound}><CatalogError message="No pudimos cargar esta solución." onRetry={() => { setLoading(true); setError(null); setNotFound(false); setReload((value) => value + 1); }}/></div></CatalogShell>;
  const cover = getSolutionCover(solution); const added = selection.some((item) => item.solutionId === solution.id);
  return <CatalogShell><section className={styles.detail}><div className={styles.gallery}>{cover ? <img src={cover.url} alt={cover.alt || solution.name}/> : <div className={styles.detailPlaceholder}><b>APX</b><span>{solution.name}</span></div>}<div className={styles.thumbs}>{(solution.gallery.length ? solution.gallery : [{ id: 'placeholder' }]).map((media, index) => <button key={media.id} aria-label={`Ver imagen ${index + 1}`}>{media.url ? <img src={media.url} alt=""/> : <span>APX</span>}</button>)}</div></div><div className={styles.detailInfo}><p className={styles.eyebrow}>{category?.name}</p><h1>{solution.name}</h1><p className={styles.lead}>{solution.description}</p><div className={styles.tags}>{solution.tags.map((tag) => <span key={tag}>{tag}</span>)}</div><p className={styles.quote}>Cotización según alcance</p><button className={styles.primary} onClick={() => add(solution.id)} disabled={added}>{added ? <><Check/> Agregado a Mi proyecto</> : <>Agregar a mi proyecto <ArrowRight/></>}</button><Link className={styles.secondary} to="/solicitar-propuesta">Solicitar propuesta</Link></div></section><section className={styles.infoGrid}><div><p className={styles.eyebrow}>LO ESENCIAL</p><h2>Una solución lista para adaptarse.</h2></div><div><h3>Beneficios</h3>{solution.features.map((feature) => <p key={feature.id}><Check/>{feature.title}</p>)}</div><div><h3>Ideal para</h3><p>{solution.useCases.join(' · ')}</p><h3>Modalidad</h3><p>{solution.modalities?.join(' · ')}</p><h3>Implementación</h3><p>{solution.implementationTime}</p></div></section>{related.length > 0 && <section className={styles.section}><div className={styles.sectionTitle}><p>TAMBIÉN PUEDE INTERESARTE</p><h2>Soluciones relacionadas</h2></div><SolutionGrid items={related}/></section>}</CatalogShell>;
}
