import type { AuthSession, ProjectSelection, ServiceCategory, Solution, SolutionMedia } from './models';
import type { AdminProjectRequestDetailDto, AdminProjectRequestListDto, AdminProjectRequestQuery, AdminSolutionListItem, AdminSolutionQuery, CatalogSolutionQuery, CreateCategoryInput, CreateProjectRequestDto, CreateSolutionInput, CreateMediaUploadRequest, MediaUploadResultDto, OtpChallengeDto, PagedResult, ProjectRequestCreatedDto, ReorderCategoryItem, RequestOtpDto, UpdateCategoryInput, UpdateMediaMetadataRequest, UpdateSolutionInput, VerifyOtpDto } from './contracts';
import type { ProjectRequestStatus } from './models';
export interface CatalogRepository { getCategories(signal?: AbortSignal): Promise<ServiceCategory[]>; getCategoryBySlug(slug: string, signal?: AbortSignal): Promise<ServiceCategory | null>; getSolutions(query?: CatalogSolutionQuery, signal?: AbortSignal): Promise<Solution[]>; getSolutionsPage(query?: CatalogSolutionQuery, signal?: AbortSignal): Promise<PagedResult<Solution>>; getSolutionsByCategory(categoryId: string, signal?: AbortSignal): Promise<Solution[]>; getSolutionBySlug(slug: string, signal?: AbortSignal): Promise<Solution | null>; getFeaturedSolutions(signal?: AbortSignal): Promise<Solution[]>; }
export interface AdminCatalogRepository { getSolutions(query?: AdminSolutionQuery): Promise<PagedResult<AdminSolutionListItem>>; getSolutionById(id: string): Promise<Solution | null>; createSolution(input: CreateSolutionInput): Promise<Solution>; updateSolution(id: string, input: UpdateSolutionInput): Promise<Solution>; deleteSolution(id: string): Promise<void>; duplicateSolution(id: string): Promise<Solution>; publishSolution(id: string): Promise<Solution>; unpublishSolution(id: string): Promise<Solution>; getCategories(): Promise<ServiceCategory[]>; createCategory(input: CreateCategoryInput): Promise<ServiceCategory>; updateCategory(id: string, input: UpdateCategoryInput): Promise<ServiceCategory>; deleteCategory(id: string): Promise<void>; reorderCategories(items: ReorderCategoryItem[]): Promise<void>; }
export interface ProjectRequestRepository { create(request: CreateProjectRequestDto): Promise<ProjectRequestCreatedDto>; }
export interface AdminProjectRequestRepository { getRequests(query?: AdminProjectRequestQuery): Promise<PagedResult<AdminProjectRequestListDto>>; getRequest(id: string): Promise<AdminProjectRequestDetailDto>; updateStatus(id: string, status: ProjectRequestStatus, rowVersion: string): Promise<AdminProjectRequestDetailDto>; }
export interface ProjectStorage { get(): ProjectSelection[]; save(items: ProjectSelection[]): void; clear(): void; }
export interface AuthRepository { requestCode(request: RequestOtpDto): Promise<OtpChallengeDto>; verifyCode(request: VerifyOtpDto): Promise<AuthSession>; getCurrentSession(): Promise<AuthSession | null>; logout(): Promise<void>; }
export interface MediaRepository { createUpload(request: CreateMediaUploadRequest): Promise<MediaUploadResultDto>; updateMetadata(solutionId: string, mediaId: string, request: UpdateMediaMetadataRequest): Promise<SolutionMedia>; setCover(solutionId: string, mediaId: string): Promise<SolutionMedia>; delete(solutionId: string, mediaId: string): Promise<void>; }
