using System.Data;
using System.Text.Json;
using APX.Application.AdminUsers;
using APX.Application.Catalog;
using APX.Application.Common;
using APX.Domain.Admin;
using APX.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
namespace APX.Infrastructure.AdminUsers;
public sealed class EfAdminUserManagementRepository(ApxDbContext db) : IAdminUserManagementRepository
{
    public async Task<PagedResult<AdminUserListDto>> GetAsync(AdminUserListQuery q,CancellationToken ct){var query=db.AdminUsers.AsNoTracking().Where(x=>x.Status!=AdminUserStatus.Archived);if(!string.IsNullOrWhiteSpace(q.Search)){var p=$"%{q.Search.Trim()}%";query=query.Where(x=>EF.Functions.ILike(x.DisplayName,p)||(x.Email!=null&&EF.Functions.ILike(x.Email,p)));}if(!string.IsNullOrWhiteSpace(q.Role))query=query.Where(x=>x.UserRoles.Any(r=>r.Role.Name==q.Role));if(!string.IsNullOrWhiteSpace(q.Status)&&Enum.TryParse<AdminUserStatus>(q.Status,true,out var status))query=query.Where(x=>x.Status==status);var total=await query.LongCountAsync(ct);var items=await query.OrderBy(x=>x.DisplayName).ThenBy(x=>x.Id).Skip((q.Page-1)*q.PageSize).Take(q.PageSize).Select(x=>new AdminUserListDto(x.Id,x.DisplayName,x.Email!,x.UserRoles.Select(r=>r.Role.Name).First(),x.Status.ToString(),x.LastLoginAt)).ToListAsync(ct);return new(items,q.Page,q.PageSize,total,(int)Math.Ceiling(total/(double)q.PageSize));}
    public async Task<AdminUserDetailDto?> GetByIdAsync(Guid id,CancellationToken ct){var x=await db.AdminUsers.AsNoTracking().Include(u=>u.UserRoles).ThenInclude(r=>r.Role).SingleOrDefaultAsync(u=>u.Id==id,ct);if(x is null)return null;var active=await db.AdminSessions.CountAsync(s=>s.AdminUserId==id&&s.RevokedAt==null&&s.ExpiresAt>DateTimeOffset.UtcNow,ct);return ToDetail(x,active);}
    public Task<bool> EmailExistsAsync(string email,CancellationToken ct)=>db.AdminUsers.AnyAsync(x=>x.Email!=null&&x.Email.ToLower()==email,ct);
    public async Task<Result<AdminUserDetailDto>> CreateAsync(CreateAdminUserDto request,Guid actorId,CancellationToken ct){var role=await db.Roles.SingleOrDefaultAsync(x=>x.Name==request.Role,ct);if(role is null)return Result<AdminUserDetailDto>.Failure(Errors.Validation("Invalid role.",new Dictionary<string,string[]>()));var now=DateTimeOffset.UtcNow;var user=new AdminUser{Id=Guid.NewGuid(),DisplayName=request.DisplayName,Email=request.Email,Status=AdminUserStatus.Active,CreatedAt=now,UpdatedAt=now};user.UserRoles.Add(new AdminUserRole{RoleId=role.Id});db.AdminUsers.Add(user);Audit(actorId,user.Id,"AdminUserCreated",null,new{user.DisplayName,user.Email,Role=request.Role,Status="Active"});try{await db.SaveChangesAsync(ct);}catch(DbUpdateException){return Result<AdminUserDetailDto>.Failure(Errors.Conflict("admin_email_conflict","An admin user with this email already exists."));}return Result<AdminUserDetailDto>.Success((await GetByIdAsync(user.Id,ct))!);}
    public async Task<Result<AdminUserDetailDto>> UpdateAsync(Guid id,UpdateAdminUserDto request,Guid actorId,CancellationToken ct){await using var tx=await db.Database.BeginTransactionAsync(IsolationLevel.Serializable,ct);var user=await db.AdminUsers.Include(x=>x.UserRoles).ThenInclude(x=>x.Role).SingleOrDefaultAsync(x=>x.Id==id,ct);if(user is null)return Result<AdminUserDetailDto>.Failure(Errors.NotFound("user_not_found","Admin user was not found."));if(!uint.TryParse(request.RowVersion,out var version))return Result<AdminUserDetailDto>.Failure(Errors.Validation("Invalid row version.",new Dictionary<string,string[]>{{"rowVersion",["Invalid."]}}));var current=user.UserRoles.Select(x=>x.Role.Name).FirstOrDefault()??"Viewer";if(current=="Admin"&&request.Role!="Admin"&&await ActiveAdminCount(ct)<=1)return Result<AdminUserDetailDto>.Failure(Errors.Conflict("last_active_admin","The last active Admin cannot be demoted."));var role=await db.Roles.SingleAsync(x=>x.Name==request.Role,ct);var before=new{user.DisplayName,Role=current};db.Entry(user).Property(x=>x.Version).OriginalValue=version;user.DisplayName=request.DisplayName;user.UpdatedAt=DateTimeOffset.UtcNow;if(current!=request.Role){db.Set<AdminUserRole>().RemoveRange(user.UserRoles);user.UserRoles.Clear();user.UserRoles.Add(new AdminUserRole{AdminUserId=id,RoleId=role.Id});await RevokeSessions(id);Audit(actorId,id,"AdminUserRoleChanged",before,new{user.DisplayName,Role=request.Role});}else Audit(actorId,id,"AdminUserUpdated",before,new{user.DisplayName,Role=request.Role});try{await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);}catch(DbUpdateConcurrencyException){await tx.RollbackAsync(ct);return Result<AdminUserDetailDto>.Failure(Errors.Concurrency("The admin user was updated from another session."));}return Result<AdminUserDetailDto>.Success((await GetByIdAsync(id,ct))!);}
    public async Task<Result<AdminUserDetailDto>> SetActiveAsync(Guid id,bool active,string rowVersion,Guid actorId,CancellationToken ct){await using var tx=await db.Database.BeginTransactionAsync(IsolationLevel.Serializable,ct);var user=await db.AdminUsers.Include(x=>x.UserRoles).ThenInclude(x=>x.Role).SingleOrDefaultAsync(x=>x.Id==id,ct);if(user is null)return Result<AdminUserDetailDto>.Failure(Errors.NotFound("user_not_found","Admin user was not found."));if(!uint.TryParse(rowVersion,out var version))return Result<AdminUserDetailDto>.Failure(Errors.Validation("Invalid row version.",new Dictionary<string,string[]>()));if(!active&&user.Status==AdminUserStatus.Active&&user.UserRoles.Any(x=>x.Role.Name=="Admin")&&await ActiveAdminCount(ct)<=1)return Result<AdminUserDetailDto>.Failure(Errors.Conflict("last_active_admin","The last active Admin cannot be disabled."));db.Entry(user).Property(x=>x.Version).OriginalValue=version;var before=user.Status;user.Status=active?AdminUserStatus.Active:AdminUserStatus.Disabled;user.UpdatedAt=DateTimeOffset.UtcNow;if(!active)await RevokeSessions(id);Audit(actorId,id,active?"AdminUserReactivated":"AdminUserDisabled",new{Status=before.ToString()},new{Status=user.Status.ToString()});try{await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);}catch(DbUpdateConcurrencyException){await tx.RollbackAsync(ct);return Result<AdminUserDetailDto>.Failure(Errors.Concurrency("The admin user was updated from another session."));}return Result<AdminUserDetailDto>.Success((await GetByIdAsync(id,ct))!);}
    private Task<int> ActiveAdminCount(CancellationToken ct)=>db.AdminUsers.CountAsync(x=>x.Status==AdminUserStatus.Active&&x.UserRoles.Any(r=>r.Role.Name=="Admin"),ct);
    private async Task RevokeSessions(Guid id){var now=DateTimeOffset.UtcNow;var sessions=await db.AdminSessions.Where(x=>x.AdminUserId==id&&x.RevokedAt==null).ToListAsync();foreach(var session in sessions){session.RevokedAt=now;db.AuditLog.Add(new AuditEntry{Id=Guid.NewGuid(),AdminUserId=id,EntityType="AdminSession",EntityId=session.Id,Action="SessionRevoked",CreatedAt=now});}}
    private void Audit(Guid actor,Guid entity,string action,object? before,object? after)=>db.AuditLog.Add(new AuditEntry{Id=Guid.NewGuid(),AdminUserId=actor,EntityType="AdminUser",EntityId=entity,Action=action,BeforeJson=before is null?null:JsonSerializer.Serialize(before),AfterJson=after is null?null:JsonSerializer.Serialize(after),CreatedAt=DateTimeOffset.UtcNow});
    private static AdminUserDetailDto ToDetail(AdminUser x,int active)=>new(x.Id,x.DisplayName,x.Email!,x.Status.ToString(),x.UserRoles.Select(r=>r.Role.Name).Order().ToList(),x.CreatedAt,x.UpdatedAt,x.LastLoginAt,active,x.Version.ToString());
}
