using System.Net.Mail;
using APX.Application.Catalog;
using APX.Application.Common;
namespace APX.Application.AdminUsers;
public sealed class AdminUserManagementService(IAdminUserManagementRepository repository, IAdminInvitationSender invitations)
{
    private static readonly string[] Roles = ["Admin", "Editor", "Viewer"];
    public async Task<Result<PagedResult<AdminUserListDto>>> GetAsync(AdminUserListQuery q, CancellationToken ct) { var e = new Dictionary<string,string[]>(); if (q.Page < 1) e["page"]=["Must be at least 1."]; if (q.PageSize is < 1 or > 100) e["pageSize"]=["Must be between 1 and 100."]; if (!string.IsNullOrWhiteSpace(q.Role) && !ValidRole(q.Role)) e["role"]=["Invalid role."]; if (!string.IsNullOrWhiteSpace(q.Status) && q.Status is not ("Active" or "Disabled")) e["status"]=["Invalid status."]; return e.Count > 0 ? Result<PagedResult<AdminUserListDto>>.Failure(Errors.Validation("Invalid query.",e)) : Result<PagedResult<AdminUserListDto>>.Success(await repository.GetAsync(q,ct)); }
    public async Task<Result<AdminUserDetailDto>> GetByIdAsync(Guid id,CancellationToken ct){var value=await repository.GetByIdAsync(id,ct);return value is null?Result<AdminUserDetailDto>.Failure(Errors.NotFound("user_not_found","Admin user was not found.")):Result<AdminUserDetailDto>.Success(value);}
    public async Task<Result<CreateAdminUserResultDto>> CreateAsync(CreateAdminUserDto request,Guid actorId,CancellationToken ct){var errors=Validate(request.DisplayName,request.Email,request.Role,true);if(errors.Count>0)return Result<CreateAdminUserResultDto>.Failure(Errors.Validation("Review the user fields.",errors));var normalized=request with{DisplayName=request.DisplayName.Trim(),Email=request.Email.Trim().ToLowerInvariant(),Role=CanonicalRole(request.Role)};if(await repository.EmailExistsAsync(normalized.Email,ct))return Result<CreateAdminUserResultDto>.Failure(Errors.Conflict("admin_email_conflict","An admin user with this email already exists."));var created=await repository.CreateAsync(normalized,actorId,ct);if(!created.Succeeded)return Result<CreateAdminUserResultDto>.Failure(created.Error!);var sent=await invitations.SendAsync(created.Value!,ct);return Result<CreateAdminUserResultDto>.Success(new(created.Value!,sent));}
    public Task<Result<AdminUserDetailDto>> UpdateAsync(Guid id,UpdateAdminUserDto request,Guid actorId,CancellationToken ct){var e=Validate(request.DisplayName,"valid@example.com",request.Role,false);if(string.IsNullOrWhiteSpace(request.RowVersion))e["rowVersion"]=["Required."];if(e.Count>0)return Task.FromResult(Result<AdminUserDetailDto>.Failure(Errors.Validation("Review the user fields.",e)));if(id==actorId&&!request.Role.Equals("Admin",StringComparison.OrdinalIgnoreCase))return Task.FromResult(Result<AdminUserDetailDto>.Failure(Errors.Conflict("cannot_modify_own_access","You cannot remove your own Admin role.")));return repository.UpdateAsync(id,request with{DisplayName=request.DisplayName.Trim(),Role=CanonicalRole(request.Role)},actorId,ct);}
    public Task<Result<AdminUserDetailDto>> DisableAsync(Guid id,ChangeAdminUserStatusDto request,Guid actorId,CancellationToken ct)=>id==actorId?Task.FromResult(Result<AdminUserDetailDto>.Failure(Errors.Conflict("cannot_modify_own_access","You cannot disable your own account."))):repository.SetActiveAsync(id,false,request.RowVersion,actorId,ct);
    public Task<Result<AdminUserDetailDto>> ReactivateAsync(Guid id,ChangeAdminUserStatusDto request,Guid actorId,CancellationToken ct)=>repository.SetActiveAsync(id,true,request.RowVersion,actorId,ct);
    public async Task<Result<CreateAdminUserResultDto>> ResendInvitationAsync(Guid id,CancellationToken ct){var user=await repository.GetByIdAsync(id,ct);if(user is null)return Result<CreateAdminUserResultDto>.Failure(Errors.NotFound("user_not_found","Admin user was not found."));if(user.Status!="Active")return Result<CreateAdminUserResultDto>.Failure(Errors.Conflict("admin_user_disabled","Invitations can only be sent to active users."));var sent=await invitations.SendAsync(user,ct);return Result<CreateAdminUserResultDto>.Success(new(user,sent));}
    private static Dictionary<string,string[]> Validate(string name,string email,string role,bool validateEmail){var e=new Dictionary<string,string[]>();if(string.IsNullOrWhiteSpace(name)||name.Trim().Length>180)e["displayName"]=["Required; maximum 180 characters."];if(validateEmail){try{_=new MailAddress(email.Trim());}catch{e["email"]=["Enter a valid email."];}}if(!ValidRole(role))e["role"]=["Use Admin, Editor or Viewer."];return e;}
    private static bool ValidRole(string value)=>Roles.Contains(value,StringComparer.OrdinalIgnoreCase);private static string CanonicalRole(string value)=>Roles.Single(x=>x.Equals(value,StringComparison.OrdinalIgnoreCase));
}
